LOCK TABLE ATOM_FEED IN EXCLUSIVE MODE;

LOCK TABLE ATOM_ENTRY IN EXCLUSIVE MODE;

LOCK TABLE ATOM_CATEGORY IN EXCLUSIVE MODE;

LOCK TABLE ATOM_LINK IN EXCLUSIVE MODE;

DELETE FROM ATOM_LINK;

DELETE FROM ATOM_CATEGORY;

DELETE FROM ATOM_ENTRY;

DELETE FROM ATOM_FEED;

INSERT INTO ATOM_FEED (FEED_ID) VALUES (1);